baseurl = "https://tuskbuddy.netlify.app"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "tuskbuddy.tk"
[[menu.main]]
hasChildren = false
name = "Homepage"
url = ""
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "tuskbuddy"
author_image = "images/banner-img.png"
bio = "I’m a freelance art director of unintelligible speech pathology at Roaring Branch University."
contact_form_action = "#"
copyright = "Copyright &copy; 2023. All rights, okays, and atta boys reserved."
description = "Book of both homestyle and ethnic recipes."
email = ""
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/tuskbuddy-logo.png"
mobile = ""
preloader = true
search = false
[params.cookies]
enable = false
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = false
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-github"
url = "https://www.github.com/tuskbuddy"
[[params.social]]
icon = "ti-marker"
url = "https://www.gitlab.com/tuskbuddy"
[[params.social]]
icon = "ti-youtube"
url = "https://www.youtube.com/user/ninjastealthiness"
